trigger:
- dev

pool:
  vmImage: 'ubuntu-latest'

# Define Variables
variables:
 - name: DEV_ENVIRONMENT
   value: dev
 - name: QA_ENVIRONMENT
   value: qa

stages:
  - stage: Terraform Validate
    displayName: Terraform validate
    jobs:
      - job: TerraformValidateJob
        continueOnError: false
        steps:
          - task: PublishPipelineArtifact@1
            displayName: Publish artifacts
            inputs:
              targetPath: '$(System.DefaultWorkingDirectory)/terraform-manifests'
              artifact: 'published-artifact'
              publishLocation: 'pipeline'
          
          - task: TerraformInstaller@1
            displayName: Terraform install
            inputs:
              terraformVersion: 'latest'

          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-manifests'
              backendServiceArm: 'azuredevops_azurerm_svc'
              backendAzureRmResourceGroupName: 'aks-rg-sa'
              backendAzureRmStorageAccountName: 'terraformstatefileaccoun'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: 'aks.tfstate'
          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'validate'
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-manifests'
        

          
              
            